options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # build and push the FastAPI image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/my-containers/fuel-api:latest'
      - '-f'
      - 'Dockerfile.fastapi'
      - '.'
    id: 'Build FastAPI image'

  # build and push streamlit image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/my-containers/fuel-streamlit:latest'
      - '-f'
      - 'Dockerfile.streamlit'
      - '.'
    id: 'Build Streamlit image'

# images
images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/my-containers/fuel-api:latest'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/my-containers/fuel-streamlit:latest'
